openapi: 3.0.0
info:
  title: cash_control
  version: 1.0.0
servers:
  - url: https://webservice-cash-control-server.vercel.app
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: category
  - name: auth
  - name: wallet
paths:
  /category:
    get:
      tags:
        - category
      summary: Get all categories
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /insert-category:
    post:
      tags:
        - category
      summary: Add Category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                wallet_name:
                  type: string
              example:
                wallet_name: Ovo
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /get-category/{id}:
    get:
      tags:
        - category
      summary: Get category by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /update-category/{id}:
    put:
      tags:
        - category
      summary: Update category by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                wallet_name:
                  type: string
              example:
                wallet_name: flip
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /delete-category/{id}:
    delete:
      tags:
        - category
      summary: Delete category by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /registration:
    post:
      tags:
        - auth
      summary: User Registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
              example:
                user_name: todos
                email: todos@gmail.com
                password: 1qazxsw2
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /login:
    post:
      tags:
        - auth
      summary: User Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                usernameEmail:
                  type: string
                password:
                  type: string
                  format: password
              example:
                usernameEmail: todos
                password: 1qazxsw2
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /wallet:
    get:
      tags:
        - wallet
      summary: Get all wallets
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /insert-wallet:
    post:
      tags:
        - wallet
      summary: Insert new wallet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category_id:
                  type: integer
                amount:
                  type: number
                contact:
                  type: string
                user_id:
                  type: number
              example:
                wallet_id: 5
                amount: 130000
                contact: 6285921240821
                user_id: 1
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /update-wallet/{id}:
    put:
      tags:
        - wallet
      summary: Update wallet by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                wallet_id:
                  type: integer
                amount:
                  type: number
                contact:
                  type: string
              example:
                wallet_id: 2
                amount: 132040.39
                contact: 6285921240821
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /get-wallet-user/{id}:
    get:
      tags:
        - wallet
      summary: Get wallets by user ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /get-wallet/{id}:
    get:
      tags:
        - wallet
      summary: Get wallet by wallet ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /delete-wallet/{id}:
    delete:
      tags:
        - wallet
      summary: Delete wallet by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
