openapi: 3.0.0
info:
  title: cash_control
  version: 1.0.0
servers:
  - url: https://webservice-cash-control-server.vercel.app
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: category
  - name: auth
  - name: wallet
paths:
  /category:
    get:
      tags:
        - category
      summary: Category
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /insert-category:
    post:
      tags:
        - category
      summary: Add Category
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                wallet_name: Ovo
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /get-category/2:
    get:
      tags:
        - category
      summary: category id
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /update-category/4:
    put:
      tags:
        - category
      summary: update category
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                wallet_name: flip
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /delete-category/3:
    delete:
      tags:
        - category
      summary: del by id
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /registration:
    post:
      tags:
        - auth
      summary: Registration
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_name: todos
                email: todos@gmail.com
                password: 1qazxsw2
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /login:
    post:
      tags:
        - auth
      summary: user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                usernameEmail: todos
                password: 1qazxsw2
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /wallet:
    get:
      tags:
        - wallet
      summary: wallet
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /insert-wallet:
    post:
      tags:
        - wallet
      summary: insert wallet
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                wallet_id: 5
                amount: 130000
                contact: 6285921240821
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /update-wallet/1:
    put:
      tags:
        - wallet
      summary: update wallet
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                wallet_id: 2
                amount: 132040.39
                contact: 6285921240821
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /get-wallet-user/1:
    get:
      tags:
        - wallet
      summary: get by id user
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /get-wallet/1:
    get:
      tags:
        - wallet
      summary: by wallet
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /delete-wallet/2:
    delete:
      tags:
        - wallet
      summary: by id
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
